version: '3'
services:
  jupyter:
    build: .
    platform: linux/x86_64
    image: takyam15/kaggle-automl
    container_name: jupyterlab
    command: jupyter lab --ip=0.0.0.0 --allow-root --LabApp.token=''
    ports:
     - "8888:8888"
    volumes:
     - ./code:/work/code
    tty: true
    stdin_open: true
